### ISSUE TITLE
missing header file

### ISSUE THREAD

**Issue by gf777** [yoshihikosuzuki/ClassPro#1]
Hello

I am getting this when compiling

config.status: error: cannot find input file: `gsl/Makefile.in'
...

In file included from ClassPro.c:21:0:
wall.c:9:10: fatal error: gsl/gsl_multifit.h: No such file or directory
 #include <gsl/gsl_multifit.h>

Thanks!

**Comment by yoshihikosuzuki** [comment]
Hi Giulio,

Thank you for the bug report. I fixed the way of installation of the gsl library, along with a few other modifications.
Can you please try to compile again with the latest commit of the main branch?

**Comment by gf777** [comment]
Hi @yoshihikosuzuki 

It seems to have worked now thanks! Maybe a couple of suggestions:
- it took a long time to compile, with so many dependencies maybe it would be good to have precompiled binaries?
- is there a test dataset to see that it is working as expected and assess the main features?
Thanks!

Giulio

**Comment by yoshihikosuzuki** [comment]
Thank you for the suggestions! Currently it compiles the whole GSL library although ClassPro depends only on a single header/library file in it, which is the reason why it takes such a long time. I will try to find a way to minimize the compilation time with: 1) precompiled binaries as you said, 2) partial compilation of GSL, or 3) precompiled GSL's static libraries.

Yes, a test dataset is what I should provide... I will prepare it in the next update (along with an updated README).

**Comment by gf777** [comment]
Cool! Let me know when you have the test dataset ready, keen to try it!

**Comment by yoshihikosuzuki** [comment]
I'm sorry it took me a while to get used to a new place since I have moved this March, but I finally made the first release v0.4 with a small example dataset. I have also made some bug fixes to the code itself, so I'm very happy if you could try it out. I'm also going to include prebuilt binaries in the next coming releases (I am now learning GitHub workflow).
