### ISSUE TITLE
(minor) release .tar.gz pollutes current directory

### ISSUE THREAD

**Issue by rchikhi** [yoshihikosuzuki/ClassPro#2]
Hello,

This is really minor, but the release bundle (https://github.com/yoshihikosuzuki/ClassPro/releases/download/v0.4b/classpro-v0.4b_linux.tar.gz) creates all of its files inside the current directory, which pollutes it. Instead it should create a "classpro-v0.4b/" folder. This can be achieved by compressing the folder itself (i.e.: `tar -zcvf classpro-v0.4b_linux.tar.gz classpro-v0.4b/` and not `tar -zcvf classpro-v0.4b_linux.tar.gz *` )

thanks,
Rayan

**Comment by yoshihikosuzuki** [comment]
Hi Rayan,

Right, this shouldn't have happened.... I will release v0.5 soon and will fix this at that time.

Thank you,
Yoshi

**Comment by yoshihikosuzuki** [comment]
It seems the release of the next version will take some more time, and I just manually replaced the precompiled v0.4b releases with those encapsulated with a single root dir as you suggested.

Best,
Yoshi

**Comment by rchikhi** [comment]
thanks!
