### ISSUE TITLE
how to use classpro as #include “xxxx”

### ISSUE THREAD

**Issue by Yichen-HNU** [yoshihikosuzuki/ClassPro#3]
hello, for my question: 
you know , ClassPro.c will generate the output file named mhc_reads.class。
 in  298： {fprintf(data->cfile,"%s\n%s\n+\n%s\n",header,seq,rasgn);
1, i want know how rasgn is assigned, because I want to use the two values of seq and rasgn directly based on your code. But I think your code is so good that I can't understand it for a short time。
2，If I just want to use a few variables from question 1 without using the other extra features, how can I import your tool into my project file as a package? It's like #include"".

Because I need to re-read the generated .class file and process it for quality and sequence, but these steps are too slow to perform, I want to omit the io reading part. Don't know if you can understand my question。

If you would like to answer my question, thank you very much！！！

**Comment by yoshihikosuzuki** [comment]
Hi, thanks for your question.
For now ClassPro is not implemented as a C library, so unfortunately it cannot be used in a way like "#include ClassPro.h". 

The content of `rasgn` is determined in the code block around lines 263-278 in ClassPro.c (via assigning values to `pasgn`, which shares the same memory address with `rasgn`), so after this code block you can use `rasgn` as you want.
However, the variable `rasgn` is re-used for each read, and also the function for classification (`kmer_class_thread`) is called with multi-threads (at line 575, `pthread_create(threads+t,NULL,kmer_class_thread,paramc+t);`), so it will require some modifications of ClassPro.c to internally pass the classification results for all the reads to another function outside ClassPro.c (at least you need a large amount of memory pre-allocated).

Instead (of calling ClassPro's functions in your code), I would recommend calling your function accepting `seq` and `rasgn` inside `kmer_class_thread`, around line 287.

I hope this helps you
