### ISSUE TITLE
ERROR:  ./ClassPro -v  :   Read 1: rlen (18247) != plen+Km1 (16635)

### ISSUE THREAD

**Issue by Yichen-HNU** [yoshihikosuzuki/ClassPro#4]
i dont know why this error:

**(base) lyc@server /home/work/lyc/tools/hamper_porec_hifi_test/ClassPro-1.0.2/bin $ ./ClassPro -v /home/work/lyc/data/human/data_21/classpro/chr21_HiFi**
Info about inputs:
    # of sequence files   = 1
    First (path,root,ext) = (/home/work/lyc/data/human/data_21/classpro, chr21_HiFi, .fq)
    FASTK outputs' root   = /home/work/lyc/data/human/data_21/classpro/chr21_HiFi
    Otput .class file     = /home/work/lyc/data/human/data_21/classpro/chr21_HiFi.class
    Temp dir path         = /home/work/lyc/tools/hamper_porec_hifi_test/ClassPro-1.0.2/bin/
    Total # of reads      = 78772
    # of reads per thread = 19693
Global histogram inspection:
    Tallest peak count    = 26 (# of k-mers = 55835832)
    Estimated (H,D) cov   = (13,26)
    Estimated R-threshold = 51
Error model not specified. Use the default error model.
Classifying 40-mers...
Read 1: rlen (18247) != plen+Km1 (16635)

**when i running  ./FastK -v -k40 -t1 -p /human/data_21/classpro/chr21_HiFi.fq :**

Partitioning 1 .fastq file into 4 parts

Determining minimizer scheme & partition for chr21_HiFi
  Estimate 2.964G 40-mers
  Dividing data into 3 blocks
  Using 5-minimizers with 1024 core prefixes

Phase 1: Partitioning K-mers into 12 Super-mer Files

  There are 78,772 reads totalling 1,484,996,518 bps

     Part:         40-mer  super-mers  ave. length
        0:    496,448,860  24,556,761         20.2
        1:    493,710,484  32,796,524         15.1
        2:    491,765,066  31,238,723         15.7
      Sum:  1,481,924,410  88,592,008         16.7

      Range 491,765,066 - 496,448,860 (0.95%)

  Resources for phase:  28.645u  2.271s  16.075w  192.3%

Phase 2: Sorting & Counting K-mers in 3 blocks

      Part:  wgt'd k-mers  savings             
         0:    88,903,258      5.6
         1:    81,032,859      6.1
         2:    77,744,706      6.3
       All:   247,680,823      6.0

  Resources for phase:  1:14.478u  6.858s  31.932w  254.7%

Phase 3 (-t option): Merging K-mer Table Parts

  There are 132,180,454 40-mers that occur 1-or-more times

  The table occupies 1.32 GB

  Resources for phase:  25.714u  3.207s  8.557w  338.0%

Phase 4 (-p option): Merging Profile Fragments

  The profiles occupy 0.53 GB

  Resources for phase:  6.338u  1.138s  3.769w  198.4%

Total Resources:  2:15.177u  13.476s  1:00.334w  246.4%  2MB

i also try k=32 and 31 , but same error

**Comment by yoshihikosuzuki** [comment]
Hi, so sorry for the late reply.

I have no clue what happened about this for now, although I suspect the profile file (.prof) is broken.
The error is generated at line 234 of ClassPro.c, so the first thing we can check would be which read this error occurred, which can be for example done by adding the following code at line 228:

```
fprintf(stderr,"id = %d, name = %s\n",id+1,header);
```

and checking which of 18247 bp and 16635 bp is true for that read by manually looking at the input fastq file. (I recommend running with a single thread.)

Or, I am happy to look into the dataset if you could provide it.

Best,
Yoshi

**Comment by yoshihikosuzuki** [comment]
Closing. Reopen if you want.
